project_id = "cupsugqsijozesuythdn"

[functions.admin-auth]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.ai-writer]
verify_jwt = false

[functions.ai-image]
verify_jwt = false
